# generate_vocab_loader.py
import psycopg2
import sys

# --- Configuration ---
DB_NAME = "smollm"
DB_USER = "sean"
DB_PASS = ""
DB_HOST = "localhost"
DB_PORT = "5432"
OUTPUT_FILE = "smollm_vocabulary_static.ailang"

def main():
    print("--- Static Vocabulary Loader Generator ---")
    
    # 1. Connect to DB
    print("[1/3] Connecting to database...")
    try:
        conn = psycopg2.connect(dbname=DB_NAME, user=DB_USER, password=DB_PASS, host=DB_HOST, port=DB_PORT)
        cur = conn.cursor()
        print("  ✓ Connected.")
    except Exception as e:
        print(f"--- FATAL: Could not connect to database: {e}")
        sys.exit(1)

    # 2. Fetch all vocabulary
    print("[2/3] Fetching all vocabulary entries...")
    try:
        cur.execute("SELECT id, token FROM vocabulary ORDER BY id;")
        vocab_data = cur.fetchall()
        print(f"  ✓ Fetched {len(vocab_data)} entries.")
    except Exception as e:
        print(f"--- FATAL: Could not fetch from 'vocabulary' table: {e}")
        cur.close()
        conn.close()
        sys.exit(1)
        
    # 3. Generate the .ailang file
    print(f"[3/3] Generating '{OUTPUT_FILE}'...")
    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("// smollm_vocabulary_static.ailang\n")
            f.write("// Auto-generated by generate_vocab_loader.py\n")
            f.write("// Contains all vocabulary words in static FixedPools for fast lookup.\n\n")
            
            # Write the lookup function
            f.write("SubRoutine.GetWordFromID {\n")
            f.write("    // Input: State.token_id\n")
            f.write("    // Output: generated_word_ptr\n")
            f.write("    Branch State.token_id {\n")
            
            words_written = 0
            for i, (token_id, token_text) in enumerate(vocab_data):
                # --- MODIFICATION ---
                # Process the first word (index 0), then every 10th word after that.
                # This implements the "load 1, skip 9" pattern.
                if i % 10 == 0:
                    escaped_token = token_text.replace('\\', '\\\\').replace('"', '\\"')
                    f.write(f'        Case {token_id}: {{ generated_word_ptr = "{escaped_token}" }}\n')
                    words_written += 1
            
            f.write("        Default: { generated_word_ptr = \"?\" }\n")
            f.write("    }\n")
            f.write("}\n")

        print(f"  ✓ Successfully wrote {words_written} cases (1 in 10 sampling).")
        print(f"\n🎉 SUCCESS! Static loader file '{OUTPUT_FILE}' has been created.")

    except Exception as e:
        print(f"--- FATAL: Could not write to output file: {e}")
    finally:
        if conn:
            cur.close()
            conn.close()

if __name__ == "__main__":
    main()
