#!/usr/bin/env python3
"""
generate_full_32d_projections.py
Generates complete 32-dimensional ProjectToQuery/Key/Value subroutines
Uses loop + Branch pattern like ring_buffer_mailbox_demo.ailang
"""

def generate_branch_cases(pool_name, prefix, count, indent=12):
    """Generate Branch cases for accessing FixedPool variables"""
    spaces = " " * indent
    lines = []
    for i in range(count):
        lines.append(f"{spaces}Case {i}: {{ {prefix} = {pool_name}.{prefix[:-4]}{i} }}")
    return "\n".join(lines)

def generate_weight_branch_cases(weight_pool, start_idx, count, indent=12):
    """Generate Branch cases for weight matrix access"""
    spaces = " " * indent
    lines = []
    for i in range(count):
        lines.append(f"{spaces}Case {start_idx + i}: {{ weight_val = {weight_pool}.w{start_idx + i} }}")
    return "\n".join(lines)

def generate_projection_subroutine(name, input_pool, weight_pool, output_pool, output_prefix):
    """Generate a complete projection subroutine (Query/Key/Value)"""
    
    code = f"""// ============================================================================
// UPGRADED: {name} - FULL 32 DIMENSIONS with loops
// ============================================================================

SubRoutine.{name} {{
    Debug("smollm.trace", level=2) {{
        PrintMessage("[{name}] ENTER\\n")
    }}
    DebugPerf.Start("{name.lower()}")
    
    // Zero out {output_pool} first
    q_idx = 0
    WhileLoop LessThan(q_idx, 32) {{
        Branch q_idx {{
"""
    
    # Generate zero-out cases
    for i in range(32):
        code += f"            Case {i}: {{ {output_pool}.{output_prefix}{i} = 0 }}\n"
    
    code += """        }
        q_idx = Add(q_idx, 1)
    }
    
    // For each output dimension q_out
    q_out = 0
    WhileLoop LessThan(q_out, 32) {
        temp_sum = 0
        
        // For each input dimension d_in
        d_in = 0
        WhileLoop LessThan(d_in, 32) {
            // Get CurrentEmbedding.d[d_in]
            Branch d_in {
"""
    
    # Generate embedding access cases
    for i in range(32):
        code += f"                Case {i}: {{ emb_val = {input_pool}.d{i} }}\n"
    
    code += """            }
            
            // Get weights[q_out * 32 + d_in]
            weight_idx = Add(Multiply(q_out, 32), d_in)
            
            Branch weight_idx {
"""
    
    # Generate weight access cases (all 1024 weights: 32x32 matrix)
    for i in range(1024):
        code += f"                Case {i}: {{ weight_val = {weight_pool}.w{i} }}\n"
    
    code += """                Default: { weight_val = 0 }
            }
            
            product = Multiply(emb_val, weight_val)
            temp_sum = Add(temp_sum, product)
            
            d_in = Add(d_in, 1)
        }
        
        // Store temp_sum into output vector
        Branch q_out {
"""
    
    # Generate output storage cases
    for i in range(32):
        code += f"            Case {i}: {{ {output_pool}.{output_prefix}{i} = temp_sum }}\n"
    
    code += f"""        }}
        
        q_out = Add(q_out, 1)
    }}
    
    Debug("smollm.trace", level=3) {{
        PrintMessage("  [{name}] {output_prefix}0=")
        PrintNumber({output_pool}.{output_prefix}0)
        PrintMessage(", {output_prefix}1=")
        PrintNumber({output_pool}.{output_prefix}1)
        PrintMessage(", {output_prefix}31=")
        PrintNumber({output_pool}.{output_prefix}31)
        PrintMessage("\\n")
    }}
    Debug("smollm.trace", level=2) {{
        PrintMessage("[{name}] EXIT\\n")
    }}
    
    DebugPerf.End("{name.lower()}")
}}

"""
    return code

def main():
    output_file = "smollm_projections_32d.ailang"
    
    with open(output_file, 'w') as f:
        f.write("// AUTO-GENERATED: Full 32-dimensional projection subroutines\n")
        f.write("// Generated by generate_full_32d_projections.py\n")
        f.write("// Uses loop + Branch pattern for efficiency\n\n")
        
        # Generate ProjectToQuery
        f.write(generate_projection_subroutine(
            "ProjectToQuery",
            "CurrentEmbedding",
            "QueryWeights",
            "QueryVector",
            "q"
        ))
        
        # Generate ProjectToKey
        f.write(generate_projection_subroutine(
            "ProjectToKey",
            "CurrentEmbedding",
            "KeyWeights",
            "KeyVector",
            "k"
        ))
        
        # Generate ProjectToValue
        f.write(generate_projection_subroutine(
            "ProjectToValue",
            "CurrentEmbedding",
            "ValueWeights",
            "ValueVector",
            "v"
        ))
    
    print(f"✓ Generated {output_file}")
    print(f"  - ProjectToQuery: 32x32 matrix multiplication")
    print(f"  - ProjectToKey: 32x32 matrix multiplication")
    print(f"  - ProjectToValue: 32x32 matrix multiplication")
    print(f"  - Each uses nested loops with Branch statements")
    print(f"  - All debug/perf instrumentation included")
    print(f"\nReplace the existing ProjectTo* subroutines in smollm_merged.ailang")
    print(f"with the contents of this file.")

if __name__ == "__main__":
    main()