#!/usr/bin/env python3
"""
generate_weight_pools.py
Generates FixedPool definitions for full 32x32 weight matrices
"""

def generate_weight_pool(pool_name, base_value=100):
    """Generate a FixedPool with 1024 weights (32x32 matrix)"""
    
    code = f'FixedPool.{pool_name} {{\n'
    
    # Generate weights in groups of 4 per line for readability
    for row in range(32):
        for col_group in range(8):  # 8 groups of 4 = 32 columns
            code += '    '
            for i in range(4):
                col = col_group * 4 + i
                weight_idx = row * 32 + col
                value = (base_value + weight_idx) % 256  # Keep values reasonable
                code += f'"w{weight_idx}": Initialize={value}'
                if weight_idx < 1023:  # Not the last weight
                    code += '   '
            code += '\n'
    
    code += '}\n\n'
    return code

def main():
    output_file = "weight_pools_32x32.ailang"
    
    with open(output_file, 'w') as f:
        f.write("// AUTO-GENERATED: Full 32x32 weight matrices\n")
        f.write("// Generated by generate_weight_pools.py\n")
        f.write("// Each pool contains 1024 weights (w0-w1023)\n\n")
        
        f.write("// Query projection weights (32x32 = 1024 weights)\n")
        f.write(generate_weight_pool("QueryWeights", 100))
        
        f.write("// Key projection weights (32x32 = 1024 weights)\n")
        f.write(generate_weight_pool("KeyWeights", 105))
        
        f.write("// Value projection weights (32x32 = 1024 weights)\n")
        f.write(generate_weight_pool("ValueWeights", 95))
    
    print(f"✓ Generated {output_file}")
    print(f"  - QueryWeights: 1024 weights (w0-w1023)")
    print(f"  - KeyWeights: 1024 weights (w0-w1023)")
    print(f"  - ValueWeights: 1024 weights (w0-w1023)")
    print(f"\nReplace your existing FixedPool definitions with these.")

if __name__ == "__main__":
    main()